period:
    start: 2022-02-01T19:00:00+09:00
    end: 2022-02-07T24:00:00+09:00
hashTag: '#冬キャス'
applicationURL: https://virtualcast-fes.connpass.com/event/235306/
cataloguePublicationDate: 2022-01-24T00:00:00+09:00
concept: 古代オリンピア
simpleTitle: 神殿
simpleSummary: オリンピア内にある、神聖な展示場
themeTitle: オリンピア
themeSummary: 古代ギリシャの建築が立ち並ぶ、台地状の都市
theme1: 機能
theme1Summary: 機能を重視したVCI
theme2: 装飾
theme2Summary: デザインを重視したVCI
applicationDeadline: 2022-01-22T24:00:00+09:00
simpleVCIUploadDeadline: 2022-01-22T24:00:00+09:00
themePreparePeriod:
    start: 2022-01-24T00:00:00+09:00
    end: 2022-01-30T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 10
maxPosterCount: 6
oneSpacePosterPlace: 2500円(税込)
twoSpacesPosterPlace: 3500円(税込)
pamphletURL: https://metamovr.booth.pm/items/3555128
