period:
    start: 2024-11-01T19:00:00+9:00
    end: 2024-11-10T24:00:00+09:00
hashTag: '#秋キャス'
applicationURL: https://connpass.com/event/331223/
cataloguePublicationDate: 2024-10-23T00:00:00+09:00
concept: 中世ロマネスク
simpleTitle: 中庭
simpleSummary: 城内にある、アーチに面した中庭
themeTitle: 城
themeSummary: 中世ヨーロッパの城塞で、内部に様々な建造物が立ち並ぶ
theme1: 昼
theme1Summary: 屋外・日中
theme2: 夜
theme2Summary: 屋外・日没後
applicationDeadline: 2024-10-20T24:00:00+09:00
simpleVCIUploadDeadline: 2024-10-20T24:00:00+09:00
themePreparePeriod:
    start: 2024-10-23T00:00:00+09:00
    end: 2024-10-29T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 10
maxPosterCount: 8
oneSpacePosterPlace: 2000円(税込)
twoSpacesPosterPlace: 3000円(税込)
pamphletURL: https://metamovr.booth.pm/items/6104635
