period:
    start: 2022-11-01T19:00:00+9:00
    end: 2022-11-10T24:00:00+09:00
hashTag: '#秋キャス'
applicationURL: https://connpass.com/event/261652/
cataloguePublicationDate: 2022-10-24T00:00:00+09:00
concept: 中世ロマネスク
simpleTitle: 中庭
simpleSummary: 城内にある、アーチに面した中庭
themeTitle: 城
themeSummary: 中世ヨーロッパの城塞で、内部に様々な建造物が立ち並ぶ
theme1: 冠《クラウン》
theme1Summary: 高貴、権力
theme2: 杖《ロッド》
theme2Summary: 知恵、魔力
applicationDeadline: 2022-10-22T24:00:00+09:00
simpleVCIUploadDeadline: 2022-10-22T24:00:00+09:00
themePreparePeriod:
    start: 2022-10-24T00:00:00+09:00
    end: 2022-10-30T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 9
maxPosterCount: 10
oneSpacePosterPlace: 2000円(税込)
twoSpacesPosterPlace: 3000円(税込)
pamphletURL: https://metamovr.booth.pm/items/4201652
