period:
    start: 2022-05-01T10:00:00+09:00
    end: 2022-05-08T24:00:00+09:00
hashTag: '#春キャス'
applicationURL: https://connpass.com/event/243728/
cataloguePublicationDate: 2022-04-23T00:00:00+09:00
concept: 古代オリンピア
simpleTitle: 神殿
simpleSummary: オリンピア内にある、神聖な展示場
themeTitle: オリンピア
themeSummary: 古代ギリシャの建築が立ち並ぶ、台地状の都市
applicationDeadline: 2022-04-22T24:00:00+09:00
simpleVCIUploadDeadline: 2022-04-22T24:00:00+09:00
themePreparePeriod:
    start: 2022-04-23T00:00:00+09:00
    end: 2022-04-29T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 10
maxPosterCount: 6
oneSpacePosterPlace: 2500円(税込)
twoSpacesPosterPlace: 3500円(税込)
pamphletURL: https://metamovr.booth.pm/items/3756828
