period:
    start: 2024-02-01T19:00:00+9:00
    end: 2024-02-10T24:00:00+09:00
hashTag: '#冬キャス'
applicationURL: https://connpass.com/event/306472/
cataloguePublicationDate: 2024-01-23T00:00:00+09:00
concept: フロンティア
simpleTitle: 展示室
simpleSummary: フロンティア内にある、室内の展示室
themeTitle: フロンティア
themeSummary: ダイナミックな高低差のある、広大な都市
theme1: 昼
theme1Summary: 屋外・日中
theme2: 夜
theme2Summary: 屋外・日没後
applicationDeadline: 2024-01-20T24:00:00+09:00
simpleVCIUploadDeadline: 2024-01-20T24:00:00+09:00
themePreparePeriod:
    start: 2024-01-23T00:00:00+09:00
    end: 2024-01-29T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 10
maxPosterCount: 10
oneSpacePosterPlace: 2000円(税込)
twoSpacesPosterPlace: 3000円(税込)
pamphletURL: https://metamovr.booth.pm/items/5377679
