period:
    start: 2023-05-01T10:00:00+9:00
    end: 2023-05-10T24:00:00+09:00
hashTag: '#春キャス'
applicationURL: https://connpass.com/event/278744/
cataloguePublicationDate: 2023-04-22T00:00:00+09:00
concept: 中世ロマネスク
simpleTitle: 中庭
simpleSummary: 城内にある、アーチに面した中庭
themeTitle: 城
themeSummary: 中世ヨーロッパの城塞で、内部に様々な建造物が立ち並ぶ
theme1: 指輪《リング》
theme1Summary: 守護、願望、円満
theme2: 魔導書《グリモワール》
theme2Summary: 呪文、知識、秘術
applicationDeadline: 2023-04-20T24:00:00+09:00
simpleVCIUploadDeadline: 2023-04-20T24:00:00+09:00
themePreparePeriod:
    start: 2023-04-22T00:00:00+09:00
    end: 2023-04-28T24:00:00+09:00
maxSimpleCount: 30
maxThemeCountPerVenue: 10
maxPosterCount: 10
oneSpacePosterPlace: 2000円(税込)
twoSpacesPosterPlace: 3000円(税込)
pamphletURL: https://metamovr.booth.pm/items/4632203
