on:
    workflow_call:

jobs:
    build:
        timeout-minutes: 5
        permissions:
            contents: read
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            # 「user-data」フォルダへ現在のデータを展開
            - id: download-artifacts-from-fetch-catalogue-build-and-deploy
              uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe #v3.1.4
              with:
                path: ./user-data
                workflow: fetch-catalogue-build-and-deploy.yaml
                name: user-data
                search_artifacts: true
                workflow_conclusion: ''
                if_no_artifact_found: ignore
            - if: ${{ steps.download-artifacts-from-fetch-catalogue-build-and-deploy.outputs.found_artifact != 'true' }}
              uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe #v3.1.4
              with:
                path: ./user-data
                workflow: on-push.yaml
                name: user-data
                search_artifacts: true
                workflow_conclusion: ''

            - uses: actions/setup-node@v3
              with:
                node-version: '20'

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v4
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - run: npm ci --production
            - run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: docs

    deploy:
        needs: build

        timeout-minutes: 2
        permissions:
            pages: write
            id-token: write
        runs-on: ubuntu-22.04
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
