on:
    push:
        branches:
          - master
    workflow_call:

# 同じワークフローが進行中の場合、それを取り消す
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                path: ./user-data
                ref: user-data
            - uses: actions/setup-node@v2
              with:
                node-version: '16'

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - run: npm ci --production
            - run: npm run build
            - uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
              with:
                github_token: ${{ github.token }}
                publish_dir: docs
