name: Googleスプレッドシートからカタログデータを取得してからビルド・デプロイ

on:
    workflow_dispatch:

# 同じワークフローが進行中の場合、それを取り消す
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    fetch-catalogue:
        uses: ./.github/workflows/fetch-catalogue.yaml
        secrets: inherit

    build-and-deploy:
        needs: fetch-catalogue
        uses: ./.github/workflows/build-and-deploy.yaml
