on:
    workflow_call:

jobs:
    fetch-catalogue:
        timeout-minutes: 5
        permissions:
            contents: write
        runs-on: ubuntu-22.04
        steps:
            - name: メインブランチをチェックアウト
              uses: actions/checkout@v3

            # 「user-data」フォルダへ現在のデータを展開
            - id: download-artifacts-from-fetch-catalogue-build-and-deploy
              uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67 #v2.26.0
              with:
                path: ./user-data
                workflow: fetch-catalogue-build-and-deploy.yaml
                name: user-data
                if_no_artifact_found: ignore
            - if: ${{ steps.download-artifacts-from-fetch-catalogue-build-and-deploy.outputs.found_artifact != 'true' }}
              uses: dawidd6/action-download-artifact@5e780fc7bbd0cac69fc73271ed86edf5dcb72d67 #v2.26.0
              with:
                path: ./user-data
                workflow: on-push.yaml
                name: user-data
                search_artifacts: true

            - name: Node.jsのインストール
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - name: npmパッケージのインストール
              run: npm ci --production

            - name: カタログデータを取得
              run: npm run fetch-catalogue
              env:
                GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
                GOOGLE_FOLDER_ID: ${{ secrets.GOOGLE_FOLDER_ID }}
                GOOGLE_SERVICE_ACCOUNT_SECRET_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_SECRET_KEY }}

            - name: カタログデータの保持
              uses: actions/upload-artifact@v3
              with:
                path: ./user-data
                name: user-data
